test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

supabase:
  service: S3
  endpoint: https://jorrpjgchxyskdkafsyd.supabase.co/storage/v1/s3
  access_key_id: <%= ENV['SUPABASE_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['SUPABASE_SECRET_ACCESS_KEY'] %>
  region: sa-east-1
  bucket: products
  force_path_style: true